services:
  image-server:
    build: ./src/image-server
    ports:
      - "5172:80"
    volumes:
      - ./images:/usr/share/nginx/html/images:ro

  imagemagick-cli:
    build: ./src/imagemagick-cli
    stdin_open: true
    tty: true
    volumes:
      - ./images:/images